# 服务相关配置
server:
  port: 80

# rpc调用相关配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# spring 数据源
spring:
  datasource:
    url: jdbc:mysql://123.57.227.142:3306/happyLife
    username: root
    password: GZZO0OO0O0.o0
    driver-class-name: com.mysql.cj.jdbc.Driver
